"""add_onboarding_availability_work_auth_to_profiles

Revision ID: 041b326c7e57
Revises: 010_add_recruiter_verification
Create Date: 2026-07-27 01:44:09.822076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041b326c7e57'
down_revision: Union[str, Sequence[str], None] = '010_add_recruiter_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter_profiles', sa.Column('company_website', sa.String(length=512), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('verification_documents', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_recruiter_profiles_verification_status'), 'recruiter_profiles', ['verification_status'], unique=False)
    op.add_column('user_profiles', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('availability', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('work_authorization', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'experience_years')
    op.drop_column('user_profiles', 'work_authorization')
    op.drop_column('user_profiles', 'availability')
    op.drop_column('user_profiles', 'onboarding_completed')
    op.drop_index(op.f('ix_recruiter_profiles_verification_status'), table_name='recruiter_profiles')
    op.drop_column('recruiter_profiles', 'verification_documents')
    op.drop_column('recruiter_profiles', 'verification_status')
    op.drop_column('recruiter_profiles', 'linkedin_url')
    op.drop_column('recruiter_profiles', 'company_website')
    # ### end Alembic commands ###
